server:
  port: ${cs.port}
spring:
  profiles:
    active: dev
  data:
    redis:
      host: ${cs.redis.host:localhost}
      port: ${cs.redis.port:6379}
      password: ${cs.redis.password:123}
      database: ${cs.redis.database:0}
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    title:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'web 端'
      paths-to-match: '/**'
      packages-to-scan: com.ustc.socket.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  documents:
    - group: 1.0版本
      name: Yubar
      locations: classpath:sign/*
  setting:
    language: zh_cn
    footer-custom-content: Copyright @ Yu-Bar (https://github.com/Yu-Bar)